---
abstract: 'Perl XS wrapper for prvhash64/prvhash64_64m'
author:
  - 'Scott Baker <bakerscot@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.76, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Digest-prvhash64
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/your/repo
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
